### ISSUE TITLE
Can it be used on server?

### ISSUE THREAD

**Issue by exdj158** [Stoupy51/DurabilityMultiplier#1]
Work well in single player games, but does not work on spigot server

**Comment by Stoupy51** [comment]
Usually, this library perfectly works with a Spigot server.
Can I ask you what plug-ins are you running on your server? And how are you using DurabilityMultiplier and through what datapack

**Comment by exdj158** [comment]
It's working well now, seems like the problem is caused by other data packets.Thank you for your help.
